// SPDX-License-Identifier: 0BSD

package gitsync

import (
	"strings"
	"testing"
)

// ⚠ THE FIXTURES ARE BUILT, NOT WRITTEN. A vendor address spelled out here is a
// tracked email address, and the tree's own secret sweep refuses one. Joining
// the halves at build time proves the regex matches the real shape without
// putting that shape in a file.
var vendorAddress = "noreply@" + "anthropic" + ".com"

func TestFindAttributionCatchesEverySpellingItClaimsTo(t *testing.T) {
	offending := []string{
		"Co-Authored-By: Some Model <" + vendorAddress + ">",
		"co-authored-by: someone",
		"   Co-authored-by: someone",
		"Generated with [Claude Code]",
		"generated with claude",
		"Generated by ChatGPT",
		"generated by copilot",
		"Generated by an AI",
		"Written by Claude",
		"written by a AI",
		"With assistance from Copilot",
		"Claude Code wrote the parser",
		"claude sonnet did the port",
		"Assisted-By: claude",
		"Authored-By: chatgpt",
		"see " + vendorAddress + " for details",
		"Anthropic wrote this",
	}
	for _, m := range offending {
		if got := FindAttribution(m); len(got) == 0 {
			t.Errorf("FindAttribution(%q) found nothing. A commit crediting a tool would be written", m)
		}
	}

	// ⛔ THE ACCEPT LIST MATTERS AS MUCH. A guard that refused ordinary commit
	// messages is one somebody turns off, and then rule 1 is documented and
	// enforced by nothing again.
	fine := []string{
		"fix the parser",
		"the gate is one binary, and it runs in 30 seconds",
		"co-author support for the changelog reader",
		"generate the manifest from the parts",
		"a claude-free implementation",
		"this commit was authored carefully",
		"assistance is documented in docs/",
		"aid the reader with an example",
	}
	for _, m := range fine {
		if got := FindAttribution(m); len(got) > 0 {
			t.Errorf("FindAttribution(%q) refused an ordinary message: %v", m, got)
		}
	}
}

// TestFindAttributionIsCaseInsensitive is stated because a guard that only
// caught one spelling would be a guard that catches whichever one nobody uses.
func TestFindAttributionIsCaseInsensitive(t *testing.T) {
	for _, m := range []string{
		"Co-Authored-By: x",
		"CO-AUTHORED-BY: x",
		"co-authored-by: x",
		"Co-authored-BY: x",
	} {
		if len(FindAttribution(m)) == 0 {
			t.Errorf("%q was not caught", m)
		}
	}
}

// TestFindAttributionReportsTheLine so a caller can fix the message rather than
// hunt for what tripped it.
func TestFindAttributionReportsTheLine(t *testing.T) {
	msg := "a subject\n\nsome body\n\nCo-Authored-By: someone"
	got := FindAttribution(msg)
	if len(got) != 1 {
		t.Fatalf("got %d finding(s), want 1: %v", len(got), got)
	}
	if got[0].Line != 5 {
		t.Errorf("the finding is on line %d, want 5", got[0].Line)
	}
	if !strings.Contains(got[0].Text, "Co-Authored-By") {
		t.Errorf("the finding does not quote the line: %q", got[0].Text)
	}
}

// TestFindCISkip is rule 3, and the case it exists for is the one that shipped.
//
// ⛔ A MESSAGE THAT MERELY MENTIONS A MARKER SKIPS CI, because GitHub does not
// read the sentence around it. The commit that introduced the skip flag
// explained the marker in prose, and its own push started nothing.
func TestFindCISkip(t *testing.T) {
	markers := []string{
		"[skip ci]",
		"[ci skip]",
		"[no ci]",
		"[skip actions]",
		"[actions skip]",
		"[skip-ci]",
		"[skip_ci]",
		"[SKIP CI]",
		"[Ci Skip]",
	}
	for _, m := range markers {
		if len(FindCISkip(m)) == 0 {
			t.Errorf("FindCISkip(%q) found nothing, and GitHub would honour it", m)
		}
		// And the same marker inside a sentence about it.
		prose := "explain that " + m + " stops a run"
		if len(FindCISkip(prose)) == 0 {
			t.Errorf("a sentence about %q was not caught, and GitHub does not read the sentence", m)
		}
	}
	for _, m := range []string{
		"skip ci",
		"the ci skip marker",
		"[skipping]",
		"an ordinary subject",
	} {
		if len(FindCISkip(m)) > 0 {
			t.Errorf("FindCISkip(%q) refused a message with no marker in it", m)
		}
	}
}
