# fill-license.ps1 - write LICENSE from a canonical text, with the holder
# filled in.
#
# ⭐ THE TWIN OF fill-license.sh. Same table, same refusals, same exit codes.
#
# The defect this exists to catch is a licence file with a placeholder still in
# it, or worse, one whose copyright line was rewritten when it should not have
# been.
#
# ⛔ A NAIVE "REPLACE THE COPYRIGHT LINE" SCRIPT CORRUPTS FIVE OF THESE TWELVE,
# and that is why this one carries a table instead of a regex:
#
#   - The GPL, AGPL and LGPL texts open with the FREE SOFTWARE FOUNDATION's
#     copyright on the licence DOCUMENT ITSELF. It is not yours and rewriting
#     it is both wrong and a licence violation. Your copyright goes in the
#     per-file header, never in LICENSE.
#   - SPDX's ISC text is a licence INSTANCE, not a template: it carries
#     Internet Systems Consortium's own copyright, and shipping it unedited
#     attributes your software to them.
#   - MPL-2.0, CC0-1.0 and Unlicense have no copyright line to fill at all.
#
# Usage:
#   pwsh -NoProfile -File scripts/common/fill-license.ps1 -Id MIT -Holder "Some Name"
#   pwsh -NoProfile -File scripts/common/fill-license.ps1 -Id MIT -Holder "Some Name" -Year 2026
#   pwsh -NoProfile -File scripts/common/fill-license.ps1 -List
#
# With no -Holder, it is read from git config. Nothing is invented: if git has
# no name configured, the script refuses rather than guessing.
#
# Exit codes: 0 written, 1 refused or a placeholder survived, 2 could not run.

[CmdletBinding()]
param(
    [string]$Id = '',
    [string]$Holder = '',
    [string]$Year = '',
    [string]$Out = 'LICENSE',
    [switch]$Force,
    [switch]$List
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$scriptDir = Split-Path -Parent $PSCommandPath
$repoRoot = (Resolve-Path (Join-Path $scriptDir '..' '..')).Path
$licDir = Join-Path $repoRoot 'LICENSES'

if (-not (Test-Path -LiteralPath $licDir -PathType Container)) {
    [Console]::Error.WriteLine("fill-license: no LICENSES directory at $licDir")
    exit 2
}

# id -> style, note
#   angle    <year> and <owner>-style placeholders
#   square   [yyyy] and [name of copyright owner], in an appendix
#   bare     YEAR, AUTHOR, EMAIL as literal words
#   none     nothing to fill
#   fsf      ⛔ the copyright line belongs to the Free Software Foundation
#   instance ⛔ the text carries somebody else's copyright
$table = [ordered]@{}
$table['MIT']           = @('angle', '')
$table['Apache-2.0']    = @('square', 'The placeholder is in the appendix, which is the header to put in your SOURCE files. Many projects ship LICENSE unmodified and put the notice in a NOTICE file instead.')
$table['BSD-2-Clause']  = @('angle', '')
$table['BSD-3-Clause']  = @('angle', '')
$table['0BSD']          = @('bare', '')
$table['ISC']           = @('instance', "SPDX ships a licence INSTANCE carrying Internet Systems Consortium's copyright. Replace that notice with your own or your software is attributed to them.")
$table['Unlicense']     = @('none', 'A public-domain dedication. There is no copyright to assert.')
$table['CC0-1.0']       = @('none', 'A public-domain dedication. Not recommended for software: it waives patent rights explicitly, which some downstream users refuse.')
$table['MPL-2.0']       = @('none', 'File-level copyleft. Per-file notices go in the source, not here.')
$table['GPL-3.0-only']  = @('fsf', "The copyright at the top is the FSF's, on the licence document. Yours goes in each source file's header. Do not edit this file.")
$table['AGPL-3.0-only'] = @('fsf', 'Same as GPL. Also triggers on network use, which is the reason to choose it over GPL.')
$table['LGPL-3.0-only'] = @('fsf', 'Same as GPL. Ships alongside a copy of GPL-3.0, which it references.')

if ($List) {
    Write-Output ('{0,-16} {1,-9} {2}' -f 'ID', 'STYLE', 'NOTE')
    foreach ($k in $table.Keys) {
        $avail = '  '
        if (-not (Test-Path -LiteralPath (Join-Path $licDir ($k + '.txt')))) { $avail = '⚠ ' }
        Write-Output ('{0}{1,-14} {2,-9} {3}' -f $avail, $k, $table[$k][0], $table[$k][1])
    }
    Write-Output ''
    Write-Output ("⚠ marks an id with no text in {0}" -f $licDir)
    exit 0
}

if (-not $Id) {
    [Console]::Error.WriteLine('fill-license: -Id is required. Use -List to see them.')
    exit 2
}

$src = Join-Path $licDir ($Id + '.txt')
if (-not (Test-Path -LiteralPath $src -PathType Leaf)) {
    [Console]::Error.WriteLine("fill-license: no text for $Id at $src")
    [Console]::Error.WriteLine('  Fetch the canonical one rather than writing it from memory:')
    [Console]::Error.WriteLine("  curl -sSL -o $src https://raw.githubusercontent.com/spdx/license-list-data/main/text/$Id.txt")
    exit 2
}

$style = 'unknown'
$note = ''
if ($table.Contains($Id)) { $style = $table[$Id][0]; $note = $table[$Id][1] }

# ⛔ The refusals. Each one is a licence where filling in a holder is wrong.
if ($style -eq 'fsf') {
    [Console]::Error.WriteLine("⛔ REFUSED: $Id")
    [Console]::Error.WriteLine('')
    [Console]::Error.WriteLine($note)
    [Console]::Error.WriteLine('')
    [Console]::Error.WriteLine('Copy the text unmodified, and put YOUR notice in each source file:')
    [Console]::Error.WriteLine("    cp $src $Out")
    [Console]::Error.WriteLine('')
    [Console]::Error.WriteLine('The per-file header the licence asks for is in its own final section.')
    exit 1
}
if ($style -eq 'instance' -and -not $Force) {
    [Console]::Error.WriteLine("⛔ REFUSED: $Id")
    [Console]::Error.WriteLine('')
    [Console]::Error.WriteLine($note)
    [Console]::Error.WriteLine('')
    [Console]::Error.WriteLine('Edit the notice by hand, then pass -Force if you still want this')
    [Console]::Error.WriteLine('script to write it. It cannot do that substitution safely on your')
    [Console]::Error.WriteLine('behalf, because the line it would rewrite is a real attribution.')
    exit 1
}

if (-not $Year) { $Year = (Get-Date).ToUniversalTime().Year.ToString() }

# ⛔ Nothing is invented. The holder comes from the machine, or the script
# refuses. A template must never carry somebody's name baked in.
if (-not $Holder -and $style -ne 'none') {
    if (Get-Command git -ErrorAction SilentlyContinue) {
        $Holder = (& git config user.name 2>$null)
        if ($LASTEXITCODE -ne 0) { $Holder = '' }
        if ($Holder) { $Holder = ($Holder | Select-Object -First 1).Trim() }
    }
    if (-not $Holder) {
        [Console]::Error.WriteLine('fill-license: no -Holder given and git has no user.name configured.')
        [Console]::Error.WriteLine('  Set one, or pass -Holder "Some Name". Nothing is guessed here.')
        exit 2
    }
    [Console]::Error.WriteLine("holder taken from git config: $Holder")
}

$lines = [System.IO.File]::ReadAllText($src) -split "`r?`n"
$outLines = New-Object System.Collections.ArrayList

switch ($style) {
    'angle' {
        foreach ($l in $lines) {
            $x = $l.Replace('<year>', $Year).Replace('<copyright holders>', $Holder).Replace('<owner>', $Holder)
            [void]$outLines.Add($x)
        }
    }
    'square' {
        foreach ($l in $lines) {
            $x = $l.Replace('[yyyy]', $Year).Replace('[name of copyright owner]', $Holder)
            [void]$outLines.Add($x)
        }
    }
    'bare' {
        # ⛔ ANCHORED TO THE FIRST LINE, and that is not tidiness. 0BSD uses the
        # bare word AUTHOR as its placeholder, and the same word appears twice
        # more in its warranty clause: "THE AUTHOR DISCLAIMS ALL WARRANTIES"
        # and "SHALL THE AUTHOR BE LIABLE". A global replace rewrote both,
        # turning a licence into a document that disclaims warranties on behalf
        # of a named person. It was caught by reading the output, not by the
        # placeholder check, which only ever asked whether a placeholder
        # SURVIVED.
        for ($i = 0; $i -lt $lines.Count; $i++) {
            if ($i -eq 0) {
                $x = $lines[$i].Replace('YEAR', $Year).Replace('AUTHOR', $Holder).Replace(' EMAIL', '').Replace('EMAIL', '')
                [void]$outLines.Add($x)
            }
            else { [void]$outLines.Add($lines[$i]) }
        }
    }
    'instance' {
        foreach ($l in $lines) {
            [void]$outLines.Add($l.Replace('<year>', $Year).Replace('<owner>', $Holder))
        }
    }
    default { foreach ($l in $lines) { [void]$outLines.Add($l) } }
}

$outPath = $Out
if (-not [System.IO.Path]::IsPathRooted($outPath)) { $outPath = Join-Path (Get-Location).Path $Out }

# ⭐ ATOMIC: a temp file in the SAME directory, then a move. A killed process
# leaves the old licence intact rather than half of one. Same directory
# matters: a move across volumes is a copy and loses the guarantee.
$tmp = $outPath + '.fill.' + $PID
[System.IO.File]::WriteAllText($tmp, ($outLines -join "`n"))
Move-Item -LiteralPath $tmp -Destination $outPath -Force

# ⛔ Verify rather than assume. A surviving placeholder is the whole defect this
# script exists to prevent, and reporting success over one would be the guard
# that cannot fail.
$written = [System.IO.File]::ReadAllText($outPath) -split "`r?`n"
$left = New-Object System.Collections.ArrayList
for ($i = 0; $i -lt $written.Count; $i++) {
    if ($written[$i] -match '<year>|<owner>|<copyright holders>|\[yyyy\]|\[name of copyright owner\]') {
        [void]$left.Add(($i + 1).ToString() + ':' + $written[$i])
    }
}
if ($left.Count -gt 0) {
    [Console]::Error.WriteLine('')
    [Console]::Error.WriteLine("⛔ a placeholder survived in $outPath")
    $left | ForEach-Object { [Console]::Error.WriteLine($_) }
    [Console]::Error.WriteLine('')
    [Console]::Error.WriteLine("The style table in this script says $Id uses the `"$style`" style.")
    [Console]::Error.WriteLine('If that is wrong, fix the table rather than the output.')
    exit 1
}

# ⛔ AND THE OTHER DIRECTION, WHICH IS THE ONE THAT ACTUALLY BIT. Asking only
# "did a placeholder survive?" cannot see an over-replacement: a global replace
# for the bare word AUTHOR rewrote 0BSD's warranty clause, and the placeholder
# check reported success over a corrupted licence.
#
# So every line of the output that is not the copyright line must appear
# verbatim in the source. Substituting into the notice is the whole job;
# changing any other line is a defect, whatever it looks like.
$srcSet = New-Object System.Collections.Generic.HashSet[string]
foreach ($l in $lines) { [void]$srcSet.Add($l) }
$over = New-Object System.Collections.ArrayList
for ($i = 0; $i -lt $written.Count; $i++) {
    $l = $written[$i]
    if (-not $l) { continue }
    if ($l -match '^Copyright' -or $l -match 'Copyright \(') { continue }
    if (-not $srcSet.Contains($l)) {
        $shown = $l
        if ($shown.Length -gt 100) { $shown = $shown.Substring(0, 100) }
        [void]$over.Add('  line ' + ($i + 1) + ': ' + $shown)
    }
}
if ($over.Count -gt 0) {
    [Console]::Error.WriteLine('')
    [Console]::Error.WriteLine("⛔ $outPath changed a line that is not the copyright notice:")
    $over | ForEach-Object { [Console]::Error.WriteLine($_) }
    [Console]::Error.WriteLine('')
    [Console]::Error.WriteLine("The substitution reached past the notice. Fix the style rule for $Id.")
    Remove-Item -LiteralPath $outPath -Force -ErrorAction SilentlyContinue
    exit 1
}

$suffix = ''
if ($style -ne 'none') { $suffix = ', ' + $Holder + ', ' + $Year }
Write-Output ('wrote ' + $Out + '  (' + $Id + $suffix + ')')
if ($note) { Write-Output ('⚠ ' + $note) }
exit 0
