#!/bin/sh
# fill-license.sh - write LICENSE from a template, with the holder filled in.
#
# The defect this exists to catch is a licence file with a placeholder still in
# it, or worse, one whose copyright line was rewritten when it should not have
# been.
#
# ⛔ A NAIVE "REPLACE THE COPYRIGHT LINE" SCRIPT CORRUPTS FIVE OF THESE TWELVE,
# and that is why this one carries a table instead of a regex:
#
#   - The GPL, AGPL and LGPL texts open with the FREE SOFTWARE FOUNDATION's
#     copyright on the licence DOCUMENT ITSELF. It is not yours and rewriting
#     it is both wrong and a licence violation. Your copyright goes in the
#     per-file header, never in LICENSE.
#   - SPDX's ISC text is a licence INSTANCE, not a template: it carries
#     Internet Systems Consortium's own copyright, and shipping it unedited
#     attributes your software to them.
#   - MPL-2.0, CC0-1.0 and Unlicense have no copyright line to fill at all.
#
# Four placeholder styles appear across the set. Each licence names its own.
#
# Usage:
#   sh scripts/common/fill-license.sh --id MIT --holder "Some Name"
#   sh scripts/common/fill-license.sh --id MIT --holder "Some Name" --year 2026
#   sh scripts/common/fill-license.sh --id Apache-2.0 --holder "Some Name" --out LICENSE
#   sh scripts/common/fill-license.sh --list
#
# With no --holder, it is read from git config. Nothing is invented: if git has
# no name configured, the script refuses rather than guessing.
#
# Exit codes: 0 written, 1 refused or a placeholder survived, 2 could not run.

set -u

ID=""
HOLDER=""
YEAR=""
OUT="LICENSE"
FORCE=0
LIST=0

while [ $# -gt 0 ]; do
  case "$1" in
    --id)     shift; ID="${1:-}" ;;
    --holder) shift; HOLDER="${1:-}" ;;
    --year)   shift; YEAR="${1:-}" ;;
    --out)    shift; OUT="${1:-}" ;;
    --force)  FORCE=1 ;;
    --list)   LIST=1 ;;
    -h|--help) awk 'NR>1 { if (/^#/) { sub(/^# ?/, ""); print } else exit }' "$0"; exit 0 ;;
    *) printf 'fill-license: unknown argument: %s\n' "$1" >&2; exit 2 ;;
  esac
  shift
done

CDPATH=''
export CDPATH
SCRIPT_DIR=$(cd -- "$(dirname -- "$0")" && pwd)
REPO_ROOT=$(cd -- "$SCRIPT_DIR/../.." && pwd)
LIC_DIR="$REPO_ROOT/LICENSES"

if [ ! -d "$LIC_DIR" ]; then
  printf 'fill-license: no LICENSES directory at %s\n' "$LIC_DIR" >&2
  exit 2
fi

# id|style|note
#   angle  <year> and <owner>-style placeholders
#   square [yyyy] and [name of copyright owner], in an appendix
#   bare   YEAR, AUTHOR, EMAIL as literal words
#   none   nothing to fill
#   fsf    ⛔ the copyright line belongs to the Free Software Foundation
#   instance ⛔ the text carries somebody else's copyright
TABLE="
MIT|angle|
Apache-2.0|square|The placeholder is in the appendix, which is the header to put in your SOURCE files. Many projects ship LICENSE unmodified and put the notice in a NOTICE file instead.
BSD-2-Clause|angle|
BSD-3-Clause|angle|
0BSD|bare|
ISC|instance|SPDX ships a licence INSTANCE carrying Internet Systems Consortium's copyright. Replace that notice with your own or your software is attributed to them.
Unlicense|none|A public-domain dedication. There is no copyright to assert.
CC0-1.0|none|A public-domain dedication. Not recommended for software: it waives patent rights explicitly, which some downstream users refuse.
MPL-2.0|none|File-level copyleft. Per-file notices go in the source, not here.
GPL-3.0-only|fsf|The copyright at the top is the FSF's, on the licence document. Yours goes in each source file's header. Do not edit this file.
AGPL-3.0-only|fsf|Same as GPL. Also triggers on network use, which is the reason to choose it over GPL.
LGPL-3.0-only|fsf|Same as GPL. Ships alongside a copy of GPL-3.0, which it references.
"

lookup() {
  printf '%s' "$TABLE" | while IFS='|' read -r t_id t_style t_note; do
    [ -z "$t_id" ] && continue
    if [ "$t_id" = "$1" ]; then printf '%s|%s' "$t_style" "$t_note"; return 0; fi
  done
}

if [ "$LIST" = "1" ]; then
  printf '%-16s %-9s %s\n' "ID" "STYLE" "NOTE"
  printf '%s' "$TABLE" | while IFS='|' read -r t_id t_style t_note; do
    [ -z "$t_id" ] && continue
    avail="  "
    [ -f "$LIC_DIR/$t_id.txt" ] || avail="⚠ "
    printf '%s%-14s %-9s %s\n' "$avail" "$t_id" "$t_style" "$t_note"
  done
  printf '\n⚠ marks an id with no text in %s\n' "$LIC_DIR"
  exit 0
fi

if [ -z "$ID" ]; then
  printf 'fill-license: --id is required. Use --list to see them.\n' >&2
  exit 2
fi

SRC="$LIC_DIR/$ID.txt"
if [ ! -f "$SRC" ]; then
  printf 'fill-license: no text for %s at %s\n' "$ID" "$SRC" >&2
  printf '  Fetch the canonical one rather than writing it from memory:\n' >&2
  printf '  curl -sSL -o %s \\\n' "$SRC" >&2
  printf '    https://raw.githubusercontent.com/spdx/license-list-data/main/text/%s.txt\n' "$ID" >&2
  exit 2
fi

INFO=$(lookup "$ID")
STYLE=$(printf '%s' "$INFO" | cut -d'|' -f1)
NOTE=$(printf '%s' "$INFO" | cut -d'|' -f2-)
[ -z "$STYLE" ] && STYLE=unknown

# ⛔ The refusals. Each one is a licence where filling in a holder is wrong.
case "$STYLE" in
  fsf)
    printf '⛔ REFUSED: %s\n\n' "$ID" >&2
    printf '%s\n\n' "$NOTE" >&2
    printf 'Copy the text unmodified, and put YOUR notice in each source file:\n\n' >&2
    printf '    cp %s %s\n\n' "$SRC" "$OUT" >&2
    printf 'The per-file header the licence asks for is in its own final section.\n' >&2
    exit 1 ;;
  instance)
    if [ "$FORCE" != "1" ]; then
      printf '⛔ REFUSED: %s\n\n' "$ID" >&2
      printf '%s\n\n' "$NOTE" >&2
      printf 'Edit the notice by hand, then pass --force if you still want this\n' >&2
      printf 'script to write it. It cannot do that substitution safely on your\n' >&2
      printf 'behalf, because the line it would rewrite is a real attribution.\n' >&2
      exit 1
    fi ;;
esac

if [ -z "$YEAR" ]; then
  YEAR=$(date -u +%Y 2>/dev/null) || YEAR=""
fi

# ⛔ Nothing is invented. The holder comes from the machine, or the script
# refuses. A template must never carry somebody's name baked in.
if [ -z "$HOLDER" ] && [ "$STYLE" != "none" ]; then
  HOLDER=$(git config user.name 2>/dev/null) || HOLDER=""
  if [ -z "$HOLDER" ]; then
    printf 'fill-license: no --holder given and git has no user.name configured.\n' >&2
    printf '  Set one, or pass --holder "Some Name". Nothing is guessed here.\n' >&2
    exit 2
  fi
  printf 'holder taken from git config: %s\n' "$HOLDER" >&2
fi

TMP="$OUT.fill.$$"
case "$STYLE" in
  angle)
    sed -e "s/<year>/$YEAR/g" \
        -e "s/<copyright holders>/$HOLDER/g" \
        -e "s/<owner>/$HOLDER/g" "$SRC" > "$TMP" ;;
  square)
    sed -e "s/\[yyyy\]/$YEAR/g" \
        -e "s/\[name of copyright owner\]/$HOLDER/g" "$SRC" > "$TMP" ;;
  bare)
    # ⛔ ANCHORED TO THE FIRST LINE, and that is not tidiness. 0BSD uses the
    # bare word AUTHOR as its placeholder, and the same word appears twice more
    # in its warranty clause: "THE AUTHOR DISCLAIMS ALL WARRANTIES" and "SHALL
    # THE AUTHOR BE LIABLE". A global replace rewrote both, turning a licence
    # into a document that disclaims warranties on behalf of a named person.
    # It was caught by reading the output, not by the placeholder check, which
    # only ever asked whether a placeholder SURVIVED.
    # ⚠ \b is a GNU sed extension and BSD sed does not have it, so this does
    # not rely on one either.
    sed -e "1s/YEAR/$YEAR/g" \
        -e "1s/AUTHOR/$HOLDER/g" \
        -e "1s/ *EMAIL//g" "$SRC" > "$TMP" ;;
  instance)
    sed -e "s/<year>/$YEAR/g" -e "s/<owner>/$HOLDER/g" "$SRC" > "$TMP" ;;
  none|unknown)
    cp "$SRC" "$TMP" ;;
esac

mv "$TMP" "$OUT"

# ⛔ Verify rather than assume. A surviving placeholder is the whole defect this
# script exists to prevent, and reporting success over one would be the guard
# that cannot fail.
LEFT=$(grep -nE '<year>|<owner>|<copyright holders>|\[yyyy\]|\[name of copyright owner\]' "$OUT" 2>/dev/null || true)
if [ -n "$LEFT" ]; then
  printf '\n⛔ a placeholder survived in %s:\n%s\n' "$OUT" "$LEFT" >&2
  printf '\nThe style table in this script says %s uses the "%s" style.\n' "$ID" "$STYLE" >&2
  printf 'If that is wrong, fix the table rather than the output.\n' >&2
  exit 1
fi

# ⛔ AND THE OTHER DIRECTION, WHICH IS THE ONE THAT ACTUALLY BIT. Asking only
# "did a placeholder survive?" cannot see an over-replacement: a global sed for
# the bare word AUTHOR rewrote 0BSD's warranty clause, and the placeholder
# check reported success over a corrupted licence.
#
# So every line of the output that is not the copyright line must appear
# verbatim in the source. Substituting into the notice is the whole job;
# changing any other line is a defect, whatever it looks like.
OVER=0
LINENO_=0
while IFS= read -r line; do
  LINENO_=$((LINENO_ + 1))
  [ -z "$line" ] && continue
  case "$line" in Copyright*|*"Copyright ("*) continue ;; esac
  if ! grep -Fxq -- "$line" "$SRC"; then
    if [ "$OVER" = "0" ]; then
      printf '\n⛔ %s changed a line that is not the copyright notice:\n' "$OUT" >&2
      OVER=1
    fi
    printf '  line %s: %s\n' "$LINENO_" "$(printf '%s' "$line" | cut -c1-100)" >&2
  fi
done < "$OUT"
if [ "$OVER" = "1" ]; then
  printf '\nThe substitution reached past the notice. Fix the style rule for %s.\n' "$ID" >&2
  rm -f "$OUT"
  exit 1
fi

printf 'wrote %s  (%s' "$OUT" "$ID"
[ "$STYLE" != "none" ] && printf ', %s, %s' "$HOLDER" "$YEAR"
printf ')\n'
[ -n "$NOTE" ] && printf '⚠ %s\n' "$NOTE"
exit 0
