// Package license writes a LICENSE file from a template, with the holder filled
// in.
//
// The defect it exists to catch is a licence file with a placeholder still in
// it, or worse, one whose copyright line was rewritten when it should not have
// been.
//
// ⛔ A NAIVE "REPLACE THE COPYRIGHT LINE" SCRIPT CORRUPTS FIVE OF THESE TWELVE,
// which is why this carries a table instead of a regex. The GPL, AGPL and LGPL
// texts open with the Free Software Foundation's copyright on the licence
// DOCUMENT ITSELF; it is not yours and rewriting it is both wrong and a licence
// violation. SPDX's ISC text is a licence INSTANCE carrying Internet Systems
// Consortium's own copyright. MPL-2.0, CC0-1.0 and Unlicense have no copyright
// line to fill at all.
//
// SPDX-License-Identifier: 0BSD
package license

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/Azathothas/ToolKit/tools/repo/internal/gitrepo"
)

// Schema versions the structured answer.
const Schema = "fill-license/1"

// Style is how one licence's placeholders are spelled, or why it has none.
type Style string

const (
	// StyleAngle is `<year>`, `<owner>`, `<copyright holders>`.
	StyleAngle Style = "angle"
	// StyleSquare is `[yyyy]` and `[name of copyright owner]`, in an appendix.
	StyleSquare Style = "square"
	// StyleBare is the literal words YEAR, AUTHOR and EMAIL.
	StyleBare Style = "bare"
	// StyleNone is a licence with nothing to fill.
	StyleNone Style = "none"
	// StyleFSF is ⛔ a copyright line belonging to the Free Software Foundation.
	StyleFSF Style = "fsf"
	// StyleInstance is ⛔ a text carrying somebody else's copyright.
	StyleInstance Style = "instance"
)

// Entry is one row of the table.
type Entry struct {
	ID    string `json:"id"`
	Style Style  `json:"style"`
	Note  string `json:"note,omitempty"`
}

// Table is the whole answer to "how is this licence filled in".
//
// ⛔ A TABLE RATHER THAN A REGEX, and the four styles are not cosmetic: each
// names a licence whose text a general substitution damages.
func Table() []Entry {
	return []Entry{
		{"MIT", StyleAngle, ""},
		{"Apache-2.0", StyleSquare, "The placeholder is in the appendix, which is the header to put in your SOURCE files. Many projects ship LICENSE unmodified and put the notice in a NOTICE file instead."},
		{"BSD-2-Clause", StyleAngle, ""},
		{"BSD-3-Clause", StyleAngle, ""},
		{"0BSD", StyleBare, ""},
		{"ISC", StyleInstance, "SPDX ships a licence INSTANCE carrying Internet Systems Consortium's copyright. Replace that notice with your own or your software is attributed to them."},
		{"Unlicense", StyleNone, "A public-domain dedication. There is no copyright to assert."},
		{"CC0-1.0", StyleNone, "A public-domain dedication. Not recommended for software: it waives patent rights explicitly, which some downstream users refuse."},
		{"MPL-2.0", StyleNone, "File-level copyleft. Per-file notices go in the source, not here."},
		{"GPL-3.0-only", StyleFSF, "The copyright at the top is the FSF's, on the licence document. Yours goes in each source file's header. Do not edit this file."},
		{"AGPL-3.0-only", StyleFSF, "Same as GPL. Also triggers on network use, which is the reason to choose it over GPL."},
		{"LGPL-3.0-only", StyleFSF, "Same as GPL. Ships alongside a copy of GPL-3.0, which it references."},
	}
}

func lookup(id string) (Entry, bool) {
	for _, e := range Table() {
		if e.ID == id {
			return e, true
		}
	}
	return Entry{ID: id, Style: "unknown"}, false
}

// Options are the flags this tool takes.
type Options struct {
	ID     string
	Holder string
	Year   string
	Out    string
	Force  bool
	List   bool
	JSON   bool
}

// Run writes the licence and returns the exit code.
//
// Exit codes: 0 written, 1 refused or a placeholder survived, 2 could not run.
func Run(opts Options, out, errOut io.Writer) int {
	repo, err := gitrepo.Open()
	if err != nil {
		fmt.Fprintf(errOut, "fill-license: %s\n", err)
		return 2
	}
	licDir := filepath.Join(repo.Root, "LICENSES")
	if st, err := os.Stat(licDir); err != nil || !st.IsDir() {
		fmt.Fprintf(errOut, "fill-license: no LICENSES directory at %s\n", licDir)
		return 2
	}

	if opts.List {
		return list(licDir, opts.JSON, out)
	}
	if opts.ID == "" {
		fmt.Fprintln(errOut, "fill-license: --id is required. Use --list to see them.")
		return 2
	}

	src := filepath.Join(licDir, opts.ID+".txt")
	body, err := os.ReadFile(src)
	if err != nil {
		fmt.Fprintf(errOut, "fill-license: no text for %s at %s\n", opts.ID, src)
		fmt.Fprintln(errOut, "  Fetch the canonical one rather than writing it from memory:")
		fmt.Fprintf(errOut, "  curl -sSL -o %s \\\n", src)
		fmt.Fprintf(errOut, "    https://raw.githubusercontent.com/spdx/license-list-data/main/text/%s.txt\n", opts.ID)
		return 2
	}
	entry, _ := lookup(opts.ID)

	// ⛔ The refusals. Each is a licence where filling in a holder is wrong.
	switch entry.Style {
	case StyleFSF:
		fmt.Fprintf(errOut, "⛔ REFUSED: %s\n\n%s\n\n", opts.ID, entry.Note)
		fmt.Fprintln(errOut, "Copy the text unmodified, and put YOUR notice in each source file:")
		fmt.Fprintf(errOut, "\n    cp %s %s\n\n", src, opts.Out)
		fmt.Fprintln(errOut, "The per-file header the licence asks for is in its own final section.")
		return 1
	case StyleInstance:
		if !opts.Force {
			fmt.Fprintf(errOut, "⛔ REFUSED: %s\n\n%s\n\n", opts.ID, entry.Note)
			fmt.Fprintln(errOut, "Edit the notice by hand, then pass --force if you still want this")
			fmt.Fprintln(errOut, "tool to write it. It cannot do that substitution safely on your")
			fmt.Fprintln(errOut, "behalf, because the line it would rewrite is a real attribution.")
			return 1
		}
	}

	year := opts.Year
	if year == "" {
		year = time.Now().UTC().Format("2006")
	}

	// ⛔ NOTHING IS INVENTED. The holder comes from the machine, or this
	// refuses. A template must never carry somebody's name baked in.
	holder := opts.Holder
	if holder == "" && entry.Style != StyleNone {
		holder = repo.Config("user.name")
		if holder == "" {
			fmt.Fprintln(errOut, "fill-license: no --holder given and git has no user.name configured.")
			fmt.Fprintln(errOut, `  Set one, or pass --holder "Some Name". Nothing is guessed here.`)
			return 2
		}
		fmt.Fprintf(errOut, "holder taken from git config: %s\n", holder)
	}

	filled := Fill(string(body), entry.Style, holder, year)

	// ⛔ VERIFY RATHER THAN ASSUME, in both directions, BEFORE anything is
	// written. The shell predecessor wrote the file and then checked it, so a
	// corrupted licence existed on disk for the length of the check.
	if left := SurvivingPlaceholders(filled); len(left) > 0 {
		fmt.Fprintf(errOut, "\n⛔ a placeholder survived in %s:\n", opts.Out)
		for _, l := range left {
			fmt.Fprintf(errOut, "  line %d: %s\n", l.Line, l.Text)
		}
		fmt.Fprintf(errOut, "\nThe style table says %s uses the %q style.\n", opts.ID, entry.Style)
		fmt.Fprintln(errOut, "If that is wrong, fix the table rather than the output.")
		return 1
	}
	if over := OverReplaced(string(body), filled); len(over) > 0 {
		fmt.Fprintf(errOut, "\n⛔ %s would change a line that is not the copyright notice:\n", opts.Out)
		for _, l := range over {
			fmt.Fprintf(errOut, "  line %d: %s\n", l.Line, l.Text)
		}
		fmt.Fprintf(errOut, "\nThe substitution reached past the notice. Fix the style rule for %s.\n", opts.ID)
		fmt.Fprintln(errOut, "Nothing was written.")
		return 1
	}

	if err := os.WriteFile(opts.Out, []byte(filled), 0o644); err != nil {
		fmt.Fprintf(errOut, "fill-license: %s\n", err)
		return 2
	}

	if opts.JSON {
		enc := json.NewEncoder(out)
		enc.SetIndent("", "  ")
		if err := enc.Encode(map[string]any{
			"schema": Schema, "id": opts.ID, "style": entry.Style,
			"holder": holder, "year": year, "out": opts.Out, "note": entry.Note,
		}); err != nil {
			fmt.Fprintf(errOut, "fill-license: %s\n", err)
			return 2
		}
		return 0
	}
	fmt.Fprintf(out, "wrote %s  (%s", opts.Out, opts.ID)
	if entry.Style != StyleNone {
		fmt.Fprintf(out, ", %s, %s", holder, year)
	}
	fmt.Fprintln(out, ")")
	if entry.Note != "" {
		fmt.Fprintf(out, "⚠ %s\n", entry.Note)
	}
	return 0
}

// Fill applies one style's substitutions.
//
// ⛔ THE BARE STYLE IS ANCHORED TO THE FIRST LINE, and that is not tidiness.
// 0BSD uses the bare word AUTHOR as its placeholder, and the same word appears
// twice more in its warranty clause: "THE AUTHOR DISCLAIMS ALL WARRANTIES" and
// "SHALL THE AUTHOR BE LIABLE". A global replace rewrote both, turning a licence
// into a document that disclaims warranties on behalf of a named person. It was
// caught by reading the output, not by the placeholder check, which only ever
// asked whether a placeholder SURVIVED.
func Fill(text string, style Style, holder, year string) string {
	switch style {
	case StyleAngle:
		r := strings.NewReplacer("<year>", year, "<copyright holders>", holder, "<owner>", holder)
		return r.Replace(text)
	case StyleSquare:
		r := strings.NewReplacer("[yyyy]", year, "[name of copyright owner]", holder)
		return r.Replace(text)
	case StyleBare:
		lines := strings.Split(text, "\n")
		if len(lines) > 0 {
			r := strings.NewReplacer("YEAR", year, "AUTHOR", holder, " EMAIL", "", "EMAIL", "")
			lines[0] = r.Replace(lines[0])
		}
		return strings.Join(lines, "\n")
	case StyleInstance:
		r := strings.NewReplacer("<year>", year, "<owner>", holder)
		return r.Replace(text)
	default:
		return text
	}
}

// Finding is one line worth reporting.
type Finding struct {
	Line int
	Text string
}

var placeholders = []string{"<year>", "<owner>", "<copyright holders>", "[yyyy]", "[name of copyright owner]"}

// SurvivingPlaceholders is the defect this tool exists to prevent.
func SurvivingPlaceholders(text string) []Finding {
	var out []Finding
	for i, line := range strings.Split(text, "\n") {
		for _, p := range placeholders {
			if strings.Contains(line, p) {
				out = append(out, Finding{Line: i + 1, Text: trim(line)})
				break
			}
		}
	}
	return out
}

// OverReplaced is the other direction, and the one that actually bit.
//
// ⛔ Asking only "did a placeholder survive?" cannot see an OVER-replacement: a
// global substitution of the bare word AUTHOR rewrote 0BSD's warranty clause,
// and the placeholder check reported success over a corrupted licence.
//
// Every line of the output that is not the copyright line must appear verbatim
// in the source. Substituting into the notice is the whole job; changing any
// other line is a defect, whatever it looks like.
func OverReplaced(src, filled string) []Finding {
	original := map[string]bool{}
	for _, line := range strings.Split(src, "\n") {
		original[line] = true
	}
	var out []Finding
	for i, line := range strings.Split(filled, "\n") {
		if strings.TrimSpace(line) == "" {
			continue
		}
		if isCopyrightLine(line) {
			continue
		}
		if !original[line] {
			out = append(out, Finding{Line: i + 1, Text: trim(line)})
		}
	}
	return out
}

func isCopyrightLine(line string) bool {
	t := strings.TrimSpace(line)
	return strings.HasPrefix(t, "Copyright") || strings.Contains(line, "Copyright (")
}

func trim(s string) string {
	if len(s) > 100 {
		return s[:100]
	}
	return s
}

func list(licDir string, asJSON bool, out io.Writer) int {
	rows := Table()
	if asJSON {
		type row struct {
			Entry
			Available bool `json:"available"`
		}
		var full []row
		for _, e := range rows {
			_, err := os.Stat(filepath.Join(licDir, e.ID+".txt"))
			full = append(full, row{Entry: e, Available: err == nil})
		}
		enc := json.NewEncoder(out)
		enc.SetIndent("", "  ")
		if err := enc.Encode(map[string]any{"schema": Schema, "licenses": full}); err != nil {
			return 2
		}
		return 0
	}
	fmt.Fprintf(out, "%-16s %-9s %s\n", "ID", "STYLE", "NOTE")
	for _, e := range rows {
		avail := "  "
		if _, err := os.Stat(filepath.Join(licDir, e.ID+".txt")); err != nil {
			avail = "⚠ "
		}
		fmt.Fprintf(out, "%s%-14s %-9s %s\n", avail, e.ID, e.Style, e.Note)
	}
	fmt.Fprintf(out, "\n⚠ marks an id with no text in %s\n", licDir)
	return 0
}
