// Package script carries wsl-toolkit.ps1 inside the executable, so one
// downloaded artefact works in an empty directory.
//
// ⛔ The copy in this directory is GENERATED by
// scripts/windows/wsl-toolkit/build.ps1 from the same parts as the tracked
// bundle, and build.ps1 -Check compares BOTH against what the parts produce.
// Go's embed directive cannot reach outside its own package directory.
//
// ⚠ The stored copy has LF and the product has CRLF, because git rewrites a
// `text eol=crlf` file on checkout and the two would otherwise embed different
// bytes per host. The build leaves no lone carriage return, so LF back to CRLF
// reconstructs the released artefact exactly.
package script

import (
	"bytes"
	"crypto/sha256"
	_ "embed"
	"encoding/hex"
	"fmt"
	"regexp"
	"sync"
)

//go:embed wsl-toolkit.ps1
var stored []byte

var product = sync.OnceValue(func() []byte {
	// Every LF becomes CRLF. The stored copy carries no lone carriage return,
	// which ToBytesAreReversible asserts rather than assumes, so this is the
	// exact inverse of what the build did on the way in.
	return bytes.ReplaceAll(stored, []byte("\n"), []byte("\r\n"))
})

// Bytes returns the product exactly as a release publishes it: a UTF-8 byte
// order mark, then CRLF endings. ⚠ Windows PowerShell 5.1 decodes a mark-less
// file with any non-ASCII byte as the system code page, so the mark is part of
// the artefact.
func Bytes() []byte {
	p := product()
	out := make([]byte, len(p))
	copy(out, p)
	return out
}

// Size is the product's length in bytes.
func Size() int { return len(product()) }

// StoredIsReversible reports whether the embedded copy can be turned back into
// the product without loss, which holds only while it carries no lone carriage
// return. A build that stopped normalising would break that silently.
func StoredIsReversible() bool { return !bytes.Contains(stored, []byte("\r")) }

var digestOnce = sync.OnceValue(func() string {
	sum := sha256.Sum256(product())
	return hex.EncodeToString(sum[:])
})

// Digest is the SHA-256 of the product bytes, which is the same object a
// release's SHA256SUMS covers. It identifies the script this executable runs.
func Digest() string { return digestOnce() }

// versionPattern reads the same assignment release.ps1 and the release workflow
// read. ⛔ A version constant declared in Go would be a second home for it.
var versionPattern = regexp.MustCompile(`(?m)^\s*\$script:ToolkitVersion\s*=\s*'([0-9]+\.[0-9]+\.[0-9]+)'\s*$`)

var versionOnce = sync.OnceValues(func() (string, error) {
	m := versionPattern.FindAllSubmatch(stored, -1)
	if len(m) != 1 {
		return "", fmt.Errorf("the embedded script carries %d version assignments and exactly one is required", len(m))
	}
	return string(m[0][1]), nil
})

// Version is the product version the embedded script declares.
func Version() (string, error) { return versionOnce() }

// digestOf lets a test assert which object Digest covers, rather than only that
// it returns hex.
func digestOf(b []byte) string {
	sum := sha256.Sum256(b)
	return hex.EncodeToString(sum[:])
}
